FROM alpine
ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache python2 && \
    python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
    rm -r /root/.cache
RUN pip install kafka && \
	pip install httplib2 
	
COPY tflrepub.py /home/root/python/
    
WORKDIR /home/root/python/

ENTRYPOINT python tflrepub.py



