services:
  spark:
    version: 3.1.2
  hdfs:
    version: 3.2.0

provider: ec2

providers:
  ec2:
    key-name: oxclo01
    identity-file: /home/oxclo/keys/oxclo01.pem
    instance-type: m3.large
    region: eu-west-1
    ami: ami-058b1b7fe545997ae   # Amazon Linux 2, eu-west-1
    user: ec2-user
    instance-profile-name: ec2-access-s3

launch:
  num-slaves: 2
  install-hdfs: False
